name = "JuliaPractice"
uuid = "d4448609-a027-4949-ac04-acfba3af2b76"
authors = ["Soichiro Jo <jo-soichiro334@g.ecc.u-tokyo.ac.jp>"]
version = "0.1.0"

[deps]
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
IJulia = "1.26.0"
LaTeXStrings = "1.4.0"
Plots = "1.40.9"
